theme: jekyll-theme-cayman
title: "Baz Does Web"
description: "Personal site of Baz"
github:
  is_project_page: false
  is_user_page: true
  repository_url: "https://github.com/santhods"
show_downloads: false
